### PR TITLE
Changed description of location.lon. Fixes #17

### LINKED ISSUE #17: API documentation v0.13 for longitude
The [API docs](https://spacedirectory.org/pages/docs.html) for `location/lon` is:
> Use positive values for locations west of Greenwich, and negative values for locations east of Greenwich.

It should be vice versa like +13.0° for eastern longitude.
Otherwise locations of [FIXME](https://fixme.ch/cgi-bin/spaceapi.py) and [coredump](http://status.crdmp.ch/) could be wrong ;-)

### PR DESCRIPTION
**Pull request by the-metalgamer**

### CODE REVIEW

**Comment by dbrgn** [comment]
Haha, good catch :)

**Comment by the-metalgamer** [comment]
Any update on this?

**Comment by rnestler** [comment]
@the-metalgamer I think we can merge this. @gidsi Agree?

**Comment by dbrgn** [comment]
Thanks @the-metalgamer!

**Pull request merged**
