### PR TITLE
refactoring to use refs, unifies sensors

### PR DESCRIPTION
**Pull request by gidsi**
Please note that this also removes the requirement to have a location from any sensor.

Also makes use of draft-04 attribute "allOf"

### CODE REVIEW

**Comment by rnestler** [comment]
Oh this one looks nice and removes quite a lot of redundancy! But it will take some time to review it carefully, since it touches a lot of stuff.

**Comment by gidsi** [comment]
Yeah, i expected that, and im not a 100% sure if i got everything right. We should write some tests or a "default" implementation where we can check against :)

Btw, i also simplified the wind sensor, not sure why but it had another attribute key inside his own root part with the different readings inside. Didn't make sense to me.

**Comment by dbrgn** [comment]
We're in the good position that we can write tests against all current implementations :)

(That's actually one of the cases where a cache is quite useful for fast testing. Some of the endpoints are very slow.)

**Comment by gidsi** [comment]
Got stale, will redo later.

**Pull request closed without merging**
