### PR TITLE
Added mastodon key to contact and to contact.keymasters array items

### LINKED ISSUE #25: Add mastodon to contact
We could add a "mastodon" key to the contact section:

https://joinmastodon.org/

Any feedback?

### PR DESCRIPTION
**Pull request by the-metalgamer**
Fixes #25

### CODE REVIEW

**Comment by the-metalgamer** [comment]
Any update on this?

**Comment by dbrgn** [comment]
Now you merged 3acf61b into this branch :) Are you familiar with `git rebase -i` to remove that commit?

**Comment by the-metalgamer** [comment]
It should be fixed now. I don't use git that often, I'm a mercurial user!

**Comment by the-metalgamer** [comment]
Any update on this?

**Comment by dbrgn** [comment]
It's OK for me, but still waiting for feedback from @rnestler or @gidsi (here or in #25).

**Pull request merged**
