### PR TITLE
Remove stream

### PR DESCRIPTION
**Pull request by gidsi**
Nobody is using it, and frankly i have no idea what it should be used for.

### CODE REVIEW

**Comment by dbrgn** [comment]
I guess it's the video stream version of "cam"... We use "cam" for our 3D printer livecam, but if it were actual video I'd hook it up to "stream".

However, even if it has its use in general, the format (with keys "m4", "mjpeg" and "ustream") is really weird and doesn't make sense.

There is one space that uses the `/ustream` key. Can you find out which one?

**Comment by gidsi** [comment]
> I guess it's the video stream version of "cam"... We use "cam" for our 3D printer livecam, but if it were actual video I'd hook it up to "stream".

But shouldn't that be more specific instead of just `stream`? `cam` is at least used for something and i have a rough understanding what you could use it for, `stream` not at all.
Like, what are you streaming? What is it for? There isn't even a description field. 

> There is one space that uses the `/ustream` key. Can you find out which one?

Sure, its [TOG](https://www.tog.ie).

**Comment by the-metalgamer** [comment]
I think this has historic reasons. When the spaceapi was first developed, streaming wasn't a thing as it is nowadays. I think back then, ustream was one of the first streaming platforms.

I think, that the same could be implemented using #67 .

**Comment by dbrgn** [comment]
Yes, things like ustream channels could definitely be moved to the links section.

Regarding webcams, I guess those can be put at "cams" even if they send a video stream instead of single frames.

I think if spaces aren't using it and it's very unclear what the actual use cases would be, then it's better to remove it (at least for now).

**Comment by gidsi** [comment]
> Can you update the changelog?

Wops! Somehow forgot to add it.

**Pull request merged**
