### PR TITLE
Remove google+ field

### PR DESCRIPTION
**Pull request by gidsi**
Google+ is discontinued since 2019-04-02.

### CODE REVIEW

**Comment by dbrgn** [comment]
Huh, how is this still present? It was removed in #37.

**Comment by dbrgn** [comment]
It seems that this commit somehow was lost, probably during some migration. Why? We should check whether other merged PRs went missing.

**Comment by koalatux** [comment]
It was merged into the `directory` branch instead of `master` :-/

**Comment by dbrgn** [comment]
Ah, apparently. @gidsi I would prefer if you could cherry-pick that commit, so that original contributor information is retained :slightly_smiling_face:

**Comment by gidsi** [comment]
> Ah, apparently. @gidsi I would prefer if you could cherry-pick that commit, so that original contributor information is retained slightly_smiling_face

Done, force pushed to remove irrelevant history.

**Comment by dbrgn** [comment]
@gidsi can you rebase to fix the changelog conflict?

**Pull request merged**
